package ec.dmt.admin.school;
import org.springframework.http.*; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException; import java.util.*;
@RestController @RequestMapping("/api/academic-years") public class AcademicYearController {
 private final AcademicYearRepository years; private final EnrollmentRepository enrollments; private final CourseRepository courses; private final SchoolParallelRepository parallels; private final StudentRepository students;
 public AcademicYearController(AcademicYearRepository y,EnrollmentRepository e,CourseRepository c,SchoolParallelRepository p,StudentRepository s){years=y;enrollments=e;courses=c;parallels=p;students=s;}
 @GetMapping public List<View> list(){return years.findAll().stream().map(y->new View(y.getId(),y.getName(),y.getStatus())).toList();}
 @PostMapping("/setup") @Transactional public View setup(@RequestBody Setup input){if(input.name()==null||input.name().isBlank())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Nombre de año requerido"); AcademicYear year=years.findByName(input.name().trim()).orElseGet(()->years.save(new AcademicYear(input.name().trim()))); String[] names={"Primero","Segundo","Tercero","Cuarto","Quinto","Sexto","Séptimo","Octavo","Noveno","Décimo","Primero de Bachillerato","Segundo de Bachillerato","Tercero de Bachillerato"}; for(int i=0;i<names.length;i++){final int order=i+1; Course c=courses.findAll().stream().filter(x->x.getName().equalsIgnoreCase(names[order-1])).findFirst().orElseGet(()->courses.save(new Course(names[order-1],true,order,order>10?"BACHILLERATO":"EGB"))); for(String label:input.parallelNames()) if(parallels.findAll().stream().noneMatch(p->p.getCourse().getId().equals(c.getId())&&p.getName().equalsIgnoreCase(label))) parallels.save(new SchoolParallel(c,label,true)); } return new View(year.getId(),year.getName(),year.getStatus()); }
 @PostMapping("/{yearId}/promote") @Transactional public Promotion promote(@PathVariable Long yearId,@RequestBody PromotionInput input){AcademicYear target=years.findById(yearId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Año no encontrado")); if(input.sourceYearId()==null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Año origen requerido"); AcademicYear source=years.findById(input.sourceYearId()).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Año origen no encontrado")); int promoted=0,graduated=0; for(Student s:students.findAll()){SchoolParallel current=s.getParallel(); Course c=current.getCourse(); if(c.getCourseOrder()>=13){graduated++;continue;} Course next=courses.findAll().stream().filter(x->x.getCourseOrder()==c.getCourseOrder()+1).findFirst().orElse(null); if(next==null)continue; SchoolParallel destination=parallels.findAll().stream().filter(p->p.getCourse().getId().equals(next.getId())&&p.getName().equalsIgnoreCase(current.getName())).findFirst().orElseGet(()->parallels.findAll().stream().filter(p->p.getCourse().getId().equals(next.getId())).findFirst().orElse(null)); if(destination==null)continue; if(!enrollments.existsByStudentIdAndAcademicYearId(s.getId(),target.getId())){enrollments.save(new Enrollment(s,target,destination,"PROMOTED"));promoted++;} } return new Promotion(source.getName(),target.getName(),promoted,graduated); }
 public record Setup(String name,List<String> parallelNames){public Setup{if(parallelNames==null||parallelNames.isEmpty())parallelNames=List.of("A","B","C","D","E","F");}}
 public record PromotionInput(Long sourceYearId){} public record Promotion(String sourceYear,String targetYear,int promoted,int graduated){} public record View(Long id,String name,String status){}
}
